apiVersion: apps/v1
kind: Deployment
metadata:
  name: rana-deployment
  labels:
    app: rana-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rana-app
  template:
    metadata:
      labels:
        app: rana-app
    spec:
      containers:
      - name: rana-container
        image: ranasalem2412/rana_image2:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rana-service
spec:
  type: NodePort
  selector:
    app: rana-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
